apiVersion: skaffold/v2beta11
kind: Config
build:
  artifacts:
    - image: aliwatters/dkc-multi-client
      context: client
      sync:
        manual:
        - src: '**/*.css'
          dest: .
        - src: '**/*.html'
          dest: .
        - src: '**/*.js'
          dest: .
      docker:
        dockerfile: Dockerfile.dev

    - image: aliwatters/dkc-multi-server
      context: server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
        - src: '**/*.js'
          dest: .

    - image: aliwatters/dkc-multi-worker
      context: worker
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
        - src: '**/*.js'
          dest: .

  local:
    push: false

deploy:
  kubectl:
    manifests:
      - k8s/client-deployment.yaml
      - k8s/client-cluster-ip-service.yaml
      - k8s/server-deployment.yaml
      - k8s/server-cluster-ip-service.yaml
      - k8s/worker-deployment.yaml
