apiVersion: skaffold/v1beta1
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: aliwatters/dkc-multi-client
      context: client
      docker: 
        dockerfile: Dockerfile.dev
      sync:
        '**/*.js': .
        '**/*.html': .
        '**/*.css': .
deploy:
  kubectl:
    manifests:
      - k8s/client-deployment.yaml
