apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: k8s-xepi-com-tls
spec:
  secretName: k8s-xepi-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: k8s.xepi.com
  dnsNames:
    - k8s.xepi.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - k8s.xepi.com